# Generated by Django 4.2.9 on 2024-04-24 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="facultyassignment",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="facultyassignment",
            name="project_group",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="home.projectgroup",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="facultyassignment",
            unique_together={("project_group", "faculty", "role")},
        ),
        migrations.RemoveField(
            model_name="facultyassignment",
            name="project",
        ),
    ]
