# Generated by Django 4.2.9 on 2024-04-24 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_facultyassignment_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExaminerMidProjectPresentation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "format_score",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Max 20 - Formatting and clarity of presentation slides, completion of presentation on time.",
                        max_digits=4,
                    ),
                ),
                (
                    "technical_content_score",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Max 40 - Covering all significant design steps, decisions, analysis and results.",
                        max_digits=4,
                    ),
                ),
                (
                    "report_score",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Max 20 - Report formatting, report contents and conclusions.",
                        max_digits=4,
                    ),
                ),
                (
                    "project_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="examiner_mid_project_presentations",
                        to="home.projectgroup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExaminerMidProjectPresentationQA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qa_score",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Max 20 - Showing adequate knowledge and understanding of the subject and providing satisfying answers to questions.",
                        max_digits=4,
                    ),
                ),
                (
                    "presentation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qa_scores",
                        to="home.examinermidprojectpresentation",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="examiner_presentation_qas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("presentation", "student")},
            },
        ),
    ]
