# Generated by Django 4.2.9 on 2024-04-25 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_examinermidprojectpresentation_examiner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="examinermidprojectpresentation",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
