# Generated by Django 4.2.9 on 2024-04-25 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_examinermidprojectpresentation_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="midprojectpresentation",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
